# Generated by Django 5.2 on 2026-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('hostel', 'Hostel'), ('home', 'Home'), ('guardian', 'Guardian')], max_length=20),
        ),
    ]
