# Generated by Django 5.2.10 on 2026-03-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDoubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_doubts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('expert_name', models.CharField(max_length=200)),
                ('session_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('meeting_link', models.URLField(blank=True)),
                ('recording_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'expert_sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='KitTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_type', models.CharField(choices=[('laptop', 'Laptop'), ('iot_kit', 'IoT Kit'), ('books', 'Books'), ('id_card', 'ID Card'), ('other', 'Other')], max_length=20)),
                ('kit_name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'kit_tracking',
            },
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
