# Generated by Django 5.2.10 on 2026-03-10 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('courses', '0002_initial'),
        ('exams', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('is_announced', models.BooleanField(default=False)),
                ('announced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='courses.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='exams.exam')),
            ],
            options={
                'db_table': 'exam_schedules',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='TopPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_performers', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_performers', to='courses.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_performances', to='users.student')),
            ],
            options={
                'db_table': 'top_performers',
                'ordering': ['batch', 'year', 'month', 'rank'],
                'unique_together': {('student', 'batch', 'period', 'month', 'year')},
            },
        ),
    ]
